[package]
name = "ast_grammar"
version = "0.1.0"
authors = ["Andrea Mambretti <mbr@ccs.neu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
